
set(FW_MAJOR_VERSION 3)
set(FW_MINOR_VERSION 5)
set(FW_RELEASE_VERSION 1)

set(BOOT_MAJOR_VERSION 3)
set(BOOT_MINOR_VERSION 1)
set(BOOT_RELEASE_VERSION 4)

set(FW_NAME band_fw)
set(BOOT_NAME band_boot)

set(FW_NAME_V ${FW_NAME}_${FW_MAJOR_VERSION}_${FW_MINOR_VERSION}_${FW_RELEASE_VERSION})
set(BOOT_NAME_V ${BOOT_NAME}_${BOOT_MAJOR_VERSION}_${BOOT_MINOR_VERSION}_${BOOT_RELEASE_VERSION})
